## Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [1]:
Numbers = [10,25,40,50]

Print the element at index 2 from the list.

In [2]:
print(Numbers[2])

40


Print the 0th element.

In [3]:
print(Numbers[0])

10


Print the third-to-last element using a minus sign in the brackets.

In [ ]:
print(Numbers[-3])

Substitute the number 10 with the number 15.

In [4]:
Numbers[0] = 15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [5]:
del Numbers[1]
Numbers 

[15, 40, 50]

## Help Yourself with Methods

Append the number 100 to the Numbers list. 

In [15]:
Numbers = [15, 40, 50]
Numbers.append(100)
Numbers

[15, 40, 50, 100]

In [16]:
Numbers.extend([115,140])
Numbers

[15, 40, 50, 100, 115, 140]

With the help of the "extend method", add the numbers 115 an 140 to the list. 

In [17]:
print("The fourth element of the Numbers list is:", Numbers[3])

The fourth element of the Numbers list is: 100


Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [18]:
len(Numbers)

6

How many elements are there in the Numbers list?

## List Slicing

In [ ]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [19]:
Numbers[3:5]

[100, 115]

Using slicing, extract the first four elements from the list.

In [20]:
Numbers[:4]

[15, 40, 50, 100]

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [24]:
Numbers[3:]

[100, 115, 140]

Using slicing, extract the last 4 elements from the list.

In [25]:
Numbers[2:]

[50, 100, 115, 140]

Which is the position of the value 15?

In [26]:
Numbers.index(15)

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists. 

In [34]:
Two_Numbers = [1,2]
All_Numbers = [Numbers, Two_Numbers]
All_Numbers


[[15, 40, 50, 100, 115, 140], [1, 2]]

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [45]:
Numbers.sort(reverse = True)
print(Numbers)

## Sort doesnt create a copy of the list, it only sorts the list. however sorted() does create a copy as seen below

lista1 = sorted(Numbers)
print(lista)
lista2 = sorted(Numbers, reverse = True)
print(lista2)

[140, 115, 100, 50, 40, 15]
[15, 40, 50, 100, 115, 140]
[140, 115, 100, 50, 40, 15]


## Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford". 

In [46]:
Cars = ("BMW", "Dodge", "Ford")

Access the second element of this tuple.

In [47]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [49]:
name, age = 'Peter,24'.split(",")

In [51]:
print(name,age)

Peter 24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle.
Call the function with arguments 2 and 10 to verify it worked correctly.

In [53]:
def rectangle_calc(x,y):
    P = (2*x) + (2*y)
    A = x*y
    print("Area and Perimeter are: ")
    return A,P


rectangle_calc(2,10)

Area and Perimeter are: 


(20, 24)

## Dictionaries

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

This is the menu of a close-by restaurant:

In [57]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [58]:
Menu['meal_2']

'Fries'

Add a new meal - "Soup".

In [60]:
Menu["meal_5"] = "Soup"
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Hamburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Replace the Hamburger with a Cheeseburger.

In [64]:
Menu["meal_3"] = "Cheeseburger"
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 'Hamburger': 'Cheeseburger'}

Attach the Desserts list in the form of a sixth meal.

In [66]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [68]:
Menu["meal_6"] = Dessert
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 'Hamburger': 'Cheeseburger',
 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars):
10, 5, 8, 12, 5. 
Start by *Price_list = {}*.

In [72]:
Price_list= {}

Price_list[Menu["meal_1"]] = 10
Price_list[Menu["meal_2"]] = 5
Price_list[Menu["meal_3"]] = 8
Price_list[Menu["meal_4"]] = 12
Price_list[Menu["meal_5"]] = 5

Price_list

{'Spaghetti': 10, 'Fries': 5, 'Cheeseburger': 8, 'Lasagna': 12, 'Soup': 5}

Use the *.get()* method to check the price of the Spaghetti.

In [73]:
Price_list.get("Spaghetti")

10